name: Kernel Builder Samsung-J4

on:
  watch:
    types: [started]

env:
  SOURCE: https://github.com/maxregnerklos/kernel_sony_murray-1
  TOOLCHAIN: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 -b lineage-17.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initialize environment
         run: |
            sudo apt-get update
            sudo apt-get install -y build-essential kernel-package libncurses5-dev bzip2 git

       - name: Clone kernel source and compiler
         run: |
            mkdir kernel
            cd kernel
            git clone $SOURCE source
            git clone $TOOLCHAIN -b lineage-17.1 toolchain

       - name: Compile KERNEL
         run: |
            cd kernel/source
            export CROSS_COMPILE=/home/runner/work/Kernel-CI/Kernel-CI/kernel/toolchain/bin/aarch64-linux-android-
            export ARCH=arm64
            make miui_defconfig
            make -i -j$(nproc --all)

       - name: Upload Image.gz
         uses: actions/upload-artifact@v3
         with:
          7z a 1.7z *
          name: 1.7z
          path: ./
